version: '3.8' 

services:
  readlater_api:
    build:
      context: . 
      dockerfile: Dockerfile 
    container_name: readlater_api_app
    restart: always
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=articledb;Username=user;Password=password
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080 
    depends_on:
      - postgres_db 
    networks:
      - app_network

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: articledb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_gui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword 
      PGADMIN_LISTEN_PORT: 80
      SCRIPT_NAME: /pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_db
    networks:
      - app_network

  nginx:
    image: nginx:stable-alpine
    container_name: reverse_proxy
    restart: always
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pgadmin
      - readlater_api
    networks:
      - app_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_network:
    driver: bridge